name: Push Workout to Intervals.icu
on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Workout Title'
        required: true
      workout:
        description: 'Workout Description (Steps)'
        required: true
        type: string
      date:
        description: 'Date (YYYY-MM-DD)'
        required: true
          
jobs:
  push-workout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: workout
        run: | 
          CLEAN_WORKOUT=$(echo "${{ inputs.workout }}" | tr '|' '\n')
          echo "$CLEAN_WORKOUT"

      - name: Run push.py
        env:
          ATHLETE_ID: ${{ secrets.ATHLETE_ID }}
          INTERVALS_KEY: ${{ secrets.INTERVALS_KEY }}
        run: |
          python3 push.py push --confirm --name "${{ github.event.inputs.title }}" --description "CLEAN_WORKOUT" --date "${{ github.event.inputs.date }}"
